---
name: omni

services:
  omni:
    image: "iib0011/omni-tools:{{ omni.version }}"
    container_name: omni-tools
    restart: unless-stopped
    networks:
      proxy:
        aliases:
          - "omni.{{ vault.shared.general.domain }}"
    healthcheck:
      test:
        - CMD
        - wget
        - --quiet
        - --spider
        - http://127.0.0.1/
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    labels:
      traefik.enable: 'true'
      traefik.http.routers.omni.entrypoints: web
      traefik.http.routers.omni.rule: >-
        Host(`omni.{{ vault.shared.general.domain }}`)
      traefik.http.middlewares.omni-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.omni.middlewares: omni-https-redirect
      traefik.http.routers.omni-secure.entrypoints: websecure
      traefik.http.routers.omni-secure.rule: >-
        Host(`omni.{{ vault.shared.general.domain }}`)
      traefik.http.routers.omni-secure.tls: 'true'
      traefik.http.routers.omni-secure.service: omni
      traefik.http.routers.omni-secure.tls.certresolver: letsencrypt
      traefik.http.services.omni.loadbalancer.server.port: '80'
      traefik.http.services.omni.loadbalancer.passhostheader: 'true'
      traefik.docker.network: "{{ omni.proxy_network }}"

networks:
  proxy:
    external: true
    name: "{{ omni.proxy_network }}"
