---
- name: Run Homebox validation stage
  ansible.builtin.import_tasks: validate.yml

- name: Run Homebox filesystem stage
  ansible.builtin.import_tasks: filesystem.yml

- name: Run Homebox preparation stage
  ansible.builtin.import_tasks: prepare.yml

- name: Run Homebox image pull stage
  ansible.builtin.import_tasks: pull.yml

- name: Run Homebox deployment stage
  ansible.builtin.import_tasks: deploy.yml
