---
name: ddns

services:
  cloudflare-ddns:
    container_name: cloudflare-ddns
    image: "favonia/cloudflare-ddns:{{ ddns.version }}"
    restart: unless-stopped
    user: "{{ ddns.uid }}:{{ ddns.gid }}"
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    secrets:
      - cf_token
    environment:
      CLOUDFLARE_API_TOKEN_FILE: /run/secrets/cf_token
      DOMAINS: "{{ ddns.dns_domains }}"
      PROXIED: 'true'
      IP6_PROVIDER: none

networks:
  default:
    name: ddns_compose

secrets:
  cf_token:
    file: ./secrets/cf_token
